### ISSUE TITLE
Remove: Deprecated GET `/:bucket/:entry/list`

### ISSUE THREAD

**Issue by atimin** [reduct-storage/reduct-storage#142]
### Current problem

Method GET  `/:bucket/:entry/list` is a better way to get data for a time interval.  Sience v0.7.0 the list method is depricated. See #122  

### Possible solution

Let's just remove it in v1.0.0 release

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rtadepalli** [comment]
The `/list` endpoint just returned the timestamp and the size of the record, which is probably not useful for people who are looking to get the record. Deprecating this method and removing it makes sense. But, the proposed solution is that the user calls `/q` and then individually execute queries for each ID returned to get the record. So, if I have 10 records, then there will be a total of 11 queries (one to get the IDs and then 10 more for individual queries against the /<bucket_name>/<entry_name>/q=<id>` endpoint. Is this what we want? Should some sort of a bulk loading API be considered that could fetch these 10 records using one query?

**Comment by atimin** [comment]
> The /list endpoint just returned the timestamp and the size of the record, which is probably not useful for people who are looking to get the record. 

Actually, it was the only way to get a record by using its timestamp. If a user needs records for a time interval, they used /list to get the timestamps. Then they can read records by the `GET /:bucket/:entry?ts=<timestamp>` request. The problem was to create the list of timestamps and sizes and send it as a JSON array when you have millions of records..  The new approach works as an iterator and doesn't have any limits for the size of the query.

I like your idea about bulk loading, but I think it is better to discuss it here - https://github.com/reduct-storage/reduct-storage/discussions/166
